### ISSUE TITLE
Automated snap builds have stopped working

### ISSUE THREAD

**Issue by bittner** [snapcrafters/codium#11]
The current version of [codium on Snapcraft](https://snapcraft.io/codium) is 1.56.0, which is a few months behind the [latest version](https://github.com/VSCodium/vscodium/releases) (currently 1.59.1). This fact has already been noticed by our users (see https://github.com/VSCodium/vscodium/issues/798).

Is this related to [Travis CI's decision](https://blog.travis-ci.com/oss-announcement) to [move open source project repositories](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/) off of travis-ci.org and onto travis-ci.com?

Can we make this work again? Maybe migrate to GitHub Actions?

**Comment by JohnVeness** [comment]
I notice that later versions are available on the "edge" channel. I'm not sure why they have stuck with 1.56 on the "stable" channel.

**Comment by bittner** [comment]
True. The "stable" version versus an "edge" channel release probably makes sense in "Ubuntu terms" (LTS vs non-LTS releases).

However, for Codium – just as for VS Code – the "stable" version is the one that is released on a roughly monthly basis (sources: [Wikipedia](https://en.wikipedia.org/wiki/Visual_Studio_Code), [GitHub](https://github.com/microsoft/vscode/releases)). The "edge" release would probably better match VS Code's "[Insiders Build](https://code.visualstudio.com/blogs/2016/05/23/evolution-of-insiders)".

**Comment by JohnVeness** [comment]
Even the edge channel seems to have stalled now. It has 1.60.2 when the latest release from upsteam is 1.62 :(

**Comment by geekley** [comment]
Ah, ok ... I was honestly thinking you guys had stopped maintaining it or something ...

**Comment by geekley** [comment]
@popey Is this still maintained?

**Comment by popey** [comment]
Sorry, not by me.

**Comment by geekley** [comment]
Ah good to know.
It might be good idea if someone adds a "Looking for maintainers" in a README/description or something like that.

In any case I guess I'll just switch to flatpak. I have been wanting to do that for a while anyways ...

**Comment by bittner** [comment]
I believe, there is more at stake than just personal technical problems.

Who is @snapcrafters? Who at that organization wears the hat for the individual projects? Why is it possible that this snap went out of service? Can we - as a @vscodium community - take on some of the responsibility, i.e. have access to the project settings?

**Comment by popey** [comment]
The short answer is that I spent a lot of my day job maintaining snapcrafters snaps. I left the company six months ago. Nobody took over maintaining the snaps. A couple of attempts have been made to rally the troops, but nobody is spending time on this. I'd recommend bringing this up on the snapcraft forum, again. https://forum.snapcraft.io/

**Comment by JohnVeness** [comment]
It looks like @daiyam is trying to sort this, but needs someone from @snapcrafters to help. https://forum.snapcraft.io/t/transfer-request-codium/26439

**Comment by bittner** [comment]
Is this actually fixed now? I can only see that [a test ran](https://github.com/snapcrafters/codium/actions), but not any kind of deployment to the snap store.

@popey You probably know the details. Is the snap now built and pushed to the store automatically, by some hidden process?

**Comment by JohnVeness** [comment]
I see https://snapcraft.io/codium now has 1.62.3 available in "edge". I don't know what's required to get it into "stable" (maybe a manual process?)

**Comment by joelpurra** [comment]
Using v1.62.3 from the edge channel seems to work well. Thanks for the fix @diddledani!

```shell
sudo snap switch codium --channel edge
sudo snap refresh codium
```

If you so prefer, switch back to the stable channel [when this version has been promoted](https://snapcraft.io/codium).
