### ISSUE TITLE
Codium's publishing workflow

### ISSUE THREAD

**Issue by daiyam** [snapcrafters/codium#16]
Hi Snapcrafters,

I've integrated your works and used some of your tools directly into the publishing workflow of Codium (https://github.com/VSCodium/vscodium/blob/master/.github/workflows/linux.yml).
So, from now on, the snaps are going to be built and published as soon as a new release happens.
Thank you.

**Comment by GitMensch** [comment]
Why is that "open"? Maybe to drop https://github.com/snapcrafters/codium or at least https://github.com/snapcrafters/codium/blob/master/.build-trigger.txt ? Maybe to still add insiders here?

Referencing new URLs
* https://github.com/VSCodium/vscodium/blob/master/.github/workflows/stable-linux.yml
* https://github.com/VSCodium/vscodium/blob/master/.github/workflows/insiders-linux.yml

Note: is https://vscodium.com/#snap wrong now, saying that the vscodium snap comes from here?

**Comment by daiyam** [comment]
yep thx
