### ISSUE TITLE
The arm64 version of codium/68 was missing GLIBC_2.29 & GLIBC_2.28

### ISSUE THREAD

**Issue by antonyshen** [snapcrafters/codium#5]
Hi,

With latest codium snap (/snap/codium/68) it has below error when run on arm64 of (Rpi) Ubuntu:

~$ codium
/snap/codium/68/usr/share/codium/bin/../codium: /snap/core18/current/lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /lib/aarch64-linux-gnu/libdrm.so.2)
/snap/codium/68/usr/share/codium/bin/../codium: /snap/core18/current/lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /lib/aarch64-linux-gnu/libgbm.so.1)
/snap/codium/68/usr/share/codium/bin/../codium: /snap/core18/current/lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /lib/aarch64-linux-gnu/libgbm.so.1)

**Comment by popey** [comment]
Looks like upstream are having difficulties building the arm64 builds now. https://github.com/VSCodium/vscodium/issues/520

**Comment by popey** [comment]
This looks to be fixed now. Tested on a Pi 400.
