### ISSUE TITLE
Fonts are missing in VSCodium dialogs on Fedora

### ISSUE THREAD

**Issue by abitrolly** [snapcrafters/codium#6]
This is what is shown on Fedora 33.

![image](https://user-images.githubusercontent.com/8781107/98545384-75ba6f00-22a6-11eb-8954-51fd33548c90.png)

The solution is to use extensions and newer base.

https://snapcraft.io/blog/the-expandables-snapcraft-extensions-and-the-secret-code

**Comment by bkis** [comment]
Can confirm. I have the same issue (Pop!_OS 20.10, VSCodium 1.51.1 via snap):

![image](https://user-images.githubusercontent.com/9215743/100359578-09ef3a80-2ff8-11eb-846f-a97bb89a3953.png)

**Comment by bkis** [comment]
@abitrolly I see you've already been active [here](https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484) and said that this didn't fix the problem for you - but **it did for me** (at least for now), so in case anybody wants to give this a try:

```
rm -rf ~/.cache/fontconfig 
rm -rf ~/snap/codium/common/.cache
fc-cache -r
```
(taken from [here](https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/54))

**Comment by abitrolly** [comment]
@bkis it might help, but the proper solution in on the snap level.

**Comment by bkis** [comment]
@abitrolly It's only a workaround, yes. But having the complete contents of the "Open Folder" dialog changed to `□□□ □□□□□ □□` etc. (incl. my directories and files names) really raised the need for a quick solution ;)

**Comment by abitrolly** [comment]
No workaround in https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/102 helped.
```
rm -rf ~/.cache/fontconfig 
rm -rf ~/snap/codium/common/.cache
fc-cache -r
```
Doesn't work for my F33.

**Comment by jdohm** [comment]
neither does it work for me on ubuntu 20.10 VSCodium version 1.53.2

**Comment by aw73** [comment]
I'm in the same case of @abitrolly on Ubuntu 20.04.2 LTS and VS Codium 1.55.2.

At this time I have no solution. I clean fontconfig cache and remove and install again VS Codium. I also tried to change Ubuntu dialog box default change with default one (Ubuntu) but the VS Codium dialog boxes displaid only squares...

**Comment by bkis** [comment]
Maybe this helps some of the people still (or _again_) looking for a fix:  
After a system update I had this same issue all over again. I closed Codium and cleared the cache (see code in the comments above), ran Codium again - no success. After a few tries I kept Codium running and cleared the cache again, voilà! I have no idea why it worked and whether it was just a coincidence, but keeping the app open while clearing the cache seems to be worth a try.

**Comment by abitrolly** [comment]
This package is just too outdated. At the very least it could use a newer base and https://snapcraft.io/docs/gnome-3-28-extension

https://github.com/snapcrafters/codium/blob/master/snap/snapcraft.yaml

**Comment by lguenth** [comment]
> Maybe this helps some of the people still (or _again_) looking for a fix: After a system update I had this same issue all over again. I closed Codium and cleared the cache (see code in the comments above), ran Codium again - no success. After a few tries I kept Codium running and cleared the cache again, voilà! I have no idea why it worked and whether it was just a coincidence, but keeping the app open while clearing the cache seems to be worth a try.

This is the only thing that helped. New install here on Ubuntu 20.04 LTS, never used Codium, installed via snap and tried to open a help dialog for the keyboard shortcuts, bug above came up. I cleared the cache while having it open and when I tried opening the same dialog again, it worked but I had to wait a few seconds before the window appeared.

Thanks anyway for giving this advice.

**Comment by abitrolly** [comment]
1.67.1 on Fedora 36. The problem is finally fixed for me. So I am closing this as it was originally reported for Fedora.

![image](https://user-images.githubusercontent.com/8781107/168234965-05ef3e05-be74-4fa2-9f72-189be3625adb.png)
